entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby
env_variables:
  SECRET_KEY_BASE: 24b1e0518158b218b2046418fddb93f82c9ca0dc1c4fc9ad25a56eba9b602d02e93fa1e87236d480ce7ad59cc65ac4d6e25e62e79d06b749f8dcc2c4841bf63c
beta_settings:
  # The connection name of your instance on its Overview page in the Google
  # Cloud Platform Console, or use `[YOUR_PROJECT_ID]:[YOUR_REGION]:[YOUR_INSTANCE_NAME]`
  cloud_sql_instances: polarisanalytics:europe-west1:polaris-analytics
